# Use an official PostGIS image as a base image
FROM postgis/postgis:14-3.4-alpine

# Set environment variables
ENV POSTGRES_DB=geometry \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres
# Copy the init.sql file into the container
COPY db/init.sql /docker-entrypoint-initdb.d/init.sql
