"""Init table

Revision ID: dc074cab1b97
Revises: 
Create Date: 2023-11-21 19:55:32.194985

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc074cab1b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('productivity', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('coordinates', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    # ### end Alembic commands ###
